### ISSUE TITLE
routine doesn't trigger ('operationPayload' Error)

### ISSUE THREAD

**Issue by remcotim** [keatontaylor/alexa_media_player#123]
routine doesn't trigger if there's more then 1 emulated_hue lights in them.  I can have an endless amount of actions set in the routine, but it only triggers if there is not more then 1 emulated_hue switch.
Log:

```
Wed Mar 13 2019 23:22:04 GMT+0100 (Midden-Europese standaardtijd)
'operationPayload'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 148, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1133, in async_call
    self._execute_service(handler, service_call))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1155, in _execute_service
    await handler.func(service_call)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 188, in handle_service
    self._platforms.values(), func, call, service_name
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 278, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 294, in _handle_service_platform_call
    await func(entity, data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 586, in play_media
    self.alexa_api.run_routine(media_id)
  File "/config/deps/lib/python3.7/site-packages/alexapy/alexaapi.py", line 149, in run_routine
    ['deviceType']) = self._device._device_type
KeyError: 'operationPayload'
```

**Comment by remcotim** [comment]
I'm on 1.2.1 and Hassio 0.89.1 by the way

**Comment by alandtse** [comment]
Repeating some questions from the thread. Didn't realize you already posted this.

This only happens with emulated hues and not other items? Does it work if you run the Routine with the Alexa App?

**Comment by remcotim** [comment]
If I run the routine from the Alexa app, I will it runs as expected. It only happens when I add more then 1 emulated_hue entity to the routine. I tried trigger with script, automation and dev services tool. Same result.

**Comment by alandtse** [comment]
Thanks. I figured it out. 

For reference for anyone who sees this thread, smarthome components are processed in parallel and have a different nodestructure with a nested nodesToExecute instead of a operationPayload.

**Comment by alandtse** [comment]
@remcotim, are you comfortable testing a dev version of alexapy?

`pip3 install --force git+https://gitlab.com/alandtse/alexapy.git@emulated_hue`

**Comment by remcotim** [comment]
Sure, no problem. I'll test it out when I'm home from work.

**Comment by remcotim** [comment]
Is it only this file that changed:
https://gitlab.com/alandtse/alexapy/blob/emulated_hue/alexapy/alexaapi.py ?

Where would it be located in my Hass.io file structure?

**Comment by alandtse** [comment]
Yes, only file changed. I actually don't know if hass.io allows the change. I'll probably need to push it out for you to use it.
