### ISSUE TITLE
Error task exception was never retrieved (entity ID already exist)

### ISSUE THREAD

**Issue by ehendrix23** [keatontaylor/alexa_media_player#124]
Version 1.2.1; got the following error entries. HA was already running for a number of hours with Alexa working.

```
2019-03-14 05:14:03 ERROR (SyncWorker_12) [alexapy.alexaapi] An error occured accessing AlexaAPI: An exception of type ConnectionError occurred. Arguments:
(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')),)
2019-03-14 05:14:09 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/Media/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.ethan_s_echo. Platform alexa_media does not generate unique IDs
2019-03-14 05:14:09 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/Media/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: media_player.master_bedroom. Platform alexa_media does not generate unique IDs
```

It was reporting the above for every Echo I have. Looks like loss of connection, reconnects but then when reconnects it tries to create new entities. 
I also checked and it is all still working. Hence reconnecting itself went fine with existing entity IDs working.

**Comment by alandtse** [comment]
Thanks. We can probably fix the check to see if the device already exists before adding. That said, as you noted, HA already prevents the same device being created so it will create log entries but will be mostly harmless.

**Comment by alandtse** [comment]
Probably need debugging to figure out why the existing check is failing. There are two checks already. One in the discovery phase in `__init__.py` and again in the actual `setup_platform` in `media_player.py`

**Comment by alandtse** [comment]
I figured out the cause and will have a fix.
