### ISSUE TITLE
Websocket failed: KeyError: 'ubid-main'

### ISSUE THREAD

**Issue by mcc05** [keatontaylor/alexa_media_player#127]
Just upgraded to the latest version 1.2.2, and I'm running HA 0.90.b3, however it fails to start with the following error, is there something I'm missing?

```bash
019-03-17 10:15:20 DEBUG (SyncWorker_0) [alexapy.alexalogin] Logged in as xxxxxxxxx@xxxxxxxx.com
2019-03-17 10:15:20 DEBUG (SyncWorker_0) [alexapy.alexalogin] Using cookies to log in
2019-03-17 10:15:20 DEBUG (SyncWorker_0) [alexapy.alexalogin] Log in successful with cookies
2019-03-17 10:15:20 DEBUG (SyncWorker_0) [custom_components.alexa_media] Setting up Alexa devices
2019-03-17 10:15:20 ERROR (SyncWorker_0) [custom_components.alexa_media] ***********@xxxxxxxx.com: Websocket failed: 'ubid-main'
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/__init__.py", line 405, in setup_alexa
    websocket = WebsocketEchoClient(login_obj, ws_handler)
  File "/config/deps/lib/python3.7/site-packages/alexapy/alexawebsocket.py", line 37, in __init__
    url += str(self._cookies['ubid-main'])
KeyError: 'ubid-main'
```
EDIT: Fixed log formatting

**Comment by alandtse** [comment]
That looks like a bug as the cookie entry is missing from your cookies and is actually required to use websockets as it's used to build the url.

What region are you in? Are you comfortable debugging directly in python? Are you in an environment where you can edit or replace the alexapy files directly (i.e. everything but hass.io I think)?

Are you able to use the Alexa webapp at alexa.amazon.com (or whatever region you're at?) If you can, you can try to catch the WebSocket connection for your region using your browsers dev tools while on the Web player.  Here's chrome's [tutorial](https://developers.google.com/web/tools/chrome-devtools/network/).

**Comment by alandtse** [comment]
Also, let me know if you lost any functionality. It should be falling back to the 1.2.1 functionality so you shouldn't lose anything as result of websockets not working.

**Comment by Obicom** [comment]
same here .... with 1.2.2

![image](https://user-images.githubusercontent.com/25134482/54489529-8639fc80-48ad-11e9-8feb-8440a7048328.png)

**Comment by alandtse** [comment]
@Obicom The releases page.

**Comment by Obicom** [comment]
but let me mention I found no functional restrictions with this error ...
