### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by Pirol62** [keatontaylor/alexa_media_player#148]
Hi,

following error recived:
An error occured accessing AlexaAPI: An exception of type JSONDecodeError occurred. Arguments:
('Expecting value: line 8 column 1 (char 7)',)

Then may be a followup error:
Mon Apr 01 2019 14:33:04 GMT+0200 (Mitteleuropäische Sommerzeit)
Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/alexa_media/__init__.py", line 450, in <lambda>
    track_time_interval(hass, lambda now: update_devices(), scan_interval)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/alexa_media/__init__.py", line 276, in update_devices
    for device in devices:
TypeError: 'NoneType' object is not iterable

Notification does not work

**Comment by Pirol62** [comment]
Ok, please close. Maybe solved. I moved the login to !secrets. Amazon wanted to get a new captcha. Haven't seen that.
