### ISSUE TITLE
script error since 1.2.4, working fine before

### ISSUE THREAD

**Issue by partymike** [keatontaylor/alexa_media_player#155]
I use the following in a script:

`  - service: notify.alexa_media
    data_template:
      data:
        type: tts
      target:
        - '{{ states.sensor.last_alexa.state }}'
      message: >
        {{ ["something here will be spoken 1",
            "something here will be spoken 2",
            "something here will be spoken 3",
        ] | random }}`

not sure what has broken it, but since update to 1.2.4 & hassio 0.91.2 I'm getting this error - other scripts work but then they don't call "last.alexa.state":

Log Details (ERROR)
Mon Apr 08 2019 22:56:13 GMT+0100 (British Summer Time)
Error executing service <ServiceCall script.goodnight_house (c:efa7761da15d46c398ccd5176f535a8a)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 307, in recv_into
    raise timeout('The read operation timed out')
socket.timeout: The read operation timed out

any ideas?

**Comment by alandtse** [comment]
Socket errors tend to be related to something fundamental with HA and the device. If you reboot the system running HA, do you still see this error?

**Comment by partymike** [comment]
reboot did the trick, thanks for the quick response :-)
