### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by pattyland** [keatontaylor/alexa_media_player#171]
Since updating to HA 0.92.1 my instance stopped working which this error:
```
2019-04-28 21:18:25 ERROR (SyncWorker_1) [concurrent.futures] exception calling callback for <Future at 0x7f4cadf18080 state=finished raised RuntimeError>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/alexa_media/__init__.py", line 550, in setup_alexa
    update_devices()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/alexa_media/__init__.py", line 340, in update_devices
    config)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/discovery.py", line 130, in load_platform
    hass_config))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 246, in add_job
    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)
  File "uvloop/loop.pyx", line 1261, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 604, in uvloop.loop.Loop._call_soon
  File "uvloop/loop.pyx", line 608, in uvloop.loop.Loop._call_soon_handle
  File "uvloop/loop.pyx", line 637, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
```

**Comment by alandtse** [comment]
Does a reboot change anything?

**Comment by pattyland** [comment]
Unfortunately not, that was the second thing I tried after a restart of HA did not help.

**Comment by alandtse** [comment]
@keatontaylor can you take a look at [this](https://github.com/home-assistant/home-assistant/issues/23379#issuecomment-487836773) please? I think I broke something with when I split your async function into helper functions.

**Comment by alandtse** [comment]
Potentially more info from #162
