### ISSUE TITLE
get_device_preferences not found

### ISSUE THREAD

**Issue by rccoleman** [keatontaylor/alexa_media_player#177]
I think you need to move the requirement of alexapy 0.5 to the new manifest, like this:

```
{
  "domain": "alexa_media",
  "name": "alexa Media",
  "documentation": "https://github.com/keatontaylor",
  "dependencies": [],
  "codeowners": ["@keatontaylor"],
  "requirements": ["alexapy==0.5.0"]
}
```

Otherwise, I get this at boot:

```
2019-04-30 22:01:39 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/alexa_media/__init__.py", line 557, in setup_alexa
    update_devices()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/alexa_media/__init__.py", line 269, in update_devices
    preferences = AlexaAPI.get_device_preferences(login_obj)
AttributeError: type object 'AlexaAPI' has no attribute 'get_device_preferences'
```

Fixing the requirements line properly installs the new version during boot.

**Comment by rccoleman** [comment]
Ah, the problem is actually that the manifest.json isn't included in custom_components.json, so when it updated to 1.2.5 via custom_updater, it didn't pull the new version.

custom_components.json needs to look like this:
```
{
    "alexa_media": {
        "version": "1.2.5",
        "local_location": "/custom_components/alexa_media/__init__.py",
        "remote_location": "https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/alexa_media/__init__.py",
        "visit_repo": "https://github.com/keatontaylor/alexa_media_player",
        "changelog": "https://github.com/keatontaylor/alexa_media_player/wiki/Changelog",
        "resources": [
            "https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/alexa_media/const.py",
            "https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/alexa_media/media_player.py",
            "https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/alexa_media/notify.py",
            "https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/alexa_media/manifest.json"
        ]
    }
}
```

Also, need to add services.yaml if you ever change it.

**Comment by alandtse** [comment]
Oh yes. Thanks for that catch.
