### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Maurotb** [keatontaylor/alexa_media_player#187]
Hi,
i have ha 0.92.2 in docker image, i have installed custom component, and 
pip3 install alexapy inside container, in my homeassistant.log i see

2019-05-16 23:34:46 ERROR (MainThread) [homeassistant.setup] Error during setup of component alexa_media
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 156, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/alexa_media/__init__.py", line 94, in setup
    for account in config[CONF_ACCOUNTS]:
TypeError: 'NoneType' object is not subscriptable

any help?
I have tried with amazon.com and amazon.it
Thanks

**Comment by alandtse** [comment]
Please post your HA config for alexa_media (you can mask your user/email info). Please ensure you quote it so we can see the syntax.

**Comment by Maurotb** [comment]
configuration.yaml
> media_player:
>   - platform: alexa
>     email: !secret amazon_email
>     password: !secret amazon_pass
>     url: amazon.it
> 
secrets.yaml
> amazon_email: xxx@gmail.com
> amazon_pass: xxx

**Comment by alandtse** [comment]
Please follow these [instructions](https://github.com/keatontaylor/alexa_media_player/wiki/Installation-and-Configuration). Your config is wrong. It's `alexa_media` not `media_player` plus other errors.
