### ISSUE TITLE
Startup problems in HA 0.94.0b3

### ISSUE THREAD

**Issue by dreimer1986** [keatontaylor/alexa_media_player#198]
Starting with that build we have the following errors. BeautifulSoup seems to be gone:

Running on HassIO it's hard to re add it.

```
2019-06-01 11:14:22 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-06-01 11:14:22 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for zigbee2mqtt_networkmap which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-06-01 11:14:22 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for custom_updater which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-06-01 11:14:26 ERROR (MainThread) [homeassistant.setup] Error during setup of component alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 156, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/alexa_media/__init__.py", line 103, in setup
    account.get(CONF_DEBUG))
  File "/config/deps/lib/python3.7/site-packages/alexapy/alexalogin.py", line 46, in __init__
    self.login_with_cookie()
  File "/config/deps/lib/python3.7/site-packages/alexapy/alexalogin.py", line 83, in login_with_cookie
    self.login(cookies=cookies)
  File "/config/deps/lib/python3.7/site-packages/alexapy/alexalogin.py", line 172, in login
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
2019-06-01 11:14:28 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform alexa_media.notify: Unable to set up component.
2019-06-01 11:14:28 ERROR (MainThread) [homeassistant.components.notify] Unknown notification service specified
```

**Comment by balloob** [comment]
Yeah this integration or the python package it depends on needs to specify to install bs4

**Comment by dreimer1986** [comment]
B4 still the same, thus I added "beautifulsoup4==4.7.1" to manifest dependency string array and inside __init__.py for fun too. Works fine again.

**Comment by alandtse** [comment]
Thats odd. The dependency is identified in alexapy.

**Comment by dreimer1986** [comment]
Odd indeed as it worked before the update to 0.94Bx now with the dependency added to the manifest all is fine again.

**Comment by alandtse** [comment]
I'm a bit reluctant to add a subdependency in the manifest.json. @balloob, should that be the normal solution? Have you heard of any other components having to do that?

**Comment by balloob** [comment]
Hmm, that should indeed just work. Can you try this again in b5? And if still not working, remove the `deps` folder in your config.

**Comment by dreimer1986** [comment]
Seems to be working with B6 again. Thus this issue can be closed ^^
