### ISSUE TITLE
Startup problems in HA 0.94.0b4

### ISSUE THREAD

**Issue by ccorderod** [keatontaylor/alexa_media_player#202]
arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.3
timezone | Europe/Madrid
version | 0.94.0b4
virtualenv | false

```yaml
alexa_media:
  accounts:
    - email: !secret amazon_un
      password: !secret amazon_pw
      url: !secret amazon_url

New problem with this build:
2019-06-02 19:37:53 ERROR (MainThread) [homeassistant.setup] Error during setup of component alexa_media
Traceback (most recent call last):
  File "/config/deps/lib/python3.7/site-packages/alexapy/alexalogin.py", line 152, in test_loggedin
    email = get_resp.json()['authentication']['customerEmail']
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 8 column 1 (char 7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 156, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/alexa_media/__init__.py", line 103, in setup
    account.get(CONF_DEBUG))
  File "/config/deps/lib/python3.7/site-packages/alexapy/alexalogin.py", line 46, in __init__
    self.login_with_cookie()
  File "/config/deps/lib/python3.7/site-packages/alexapy/alexalogin.py", line 83, in login_with_cookie
    self.login(cookies=cookies)
  File "/config/deps/lib/python3.7/site-packages/alexapy/alexalogin.py", line 175, in login
    if (cookies is not None and self.test_loggedin(cookies)):
  File "/config/deps/lib/python3.7/site-packages/alexapy/alexalogin.py", line 153, in test_loggedin
    except (JSONDecodeError, SimpleJSONDecodeError) as ex:
UnboundLocalError: local variable 'SimpleJSONDecodeError' referenced before assignment

**Comment by alandtse** [comment]
Please confirm you've actually logged in after passing the Captcha. You may have to delete the Cookie file. 
 Check HA notifications as that will show you the Configurator.

**Comment by rbhr** [comment]
It has been for all of 94 I think.
I think bs4 needs to be a requirement or dependency in the manifest.
I solved it by opening a terminal in my HA container and running a pip3 install bs4

**Comment by ccorderod** [comment]
@alandtse @rbhr Upgraded to 0.94.0b5. Alexa media fully functional again. Thank you.

**Comment by alandtse** [comment]
Glad it worked out. There's something about the hassio environment where dependencies don't reliably load.
