### ISSUE TITLE
KeyError: 'LambdaBridge_AAA/OnGuardSmartHomeBridgeService'

### ISSUE THREAD

**Issue by alandtse** [keatontaylor/alexa_media_player#226]
**Describe the bug**
```
2019-06-23 09:59:32 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up platform alexa_media
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/alexa_media/alarm_control_panel.py", line 34, in setup_platform
    hass)  \
  File "/config/custom_components/alexa_media/alarm_control_panel.py", line 73, in __init__
    ['LambdaBridge_AAA/OnGuardSmartHomeBridgeService']
KeyError: 'LambdaBridge_AAA/OnGuardSmartHomeBridgeService'
```

**To Reproduce**
1. Start HA in the UK or other location without Alexa Guard.

**Expected behavior**
No errors

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 1.3.0
 - alexapy (version from `pip show alexapy` or HA startup): 0.7.0

**Additional context**
[Thread post](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/2799)

**Comment by glassbase** [comment]
I also get this error but my region in Canada and Guard is available here. I don't have it enabled which is maybe why I also receive this error?

**Comment by Skateboss** [comment]
I've had the same problem in the UK too

**Comment by vMeph** [comment]
same problem....

**Comment by alandtse** [comment]
Thanks we have a potential fix in the queue. Of course let me know if you're reporting the error with the proposed fix.

**Comment by mauog** [comment]
Same problem too in Italy

**Comment by Pirol62** [comment]
Same issue with already updated 0.95 in Germany

**Comment by PrathikGopal** [comment]
Same errors in India too, updated to latest 0.95
