### ISSUE TITLE
No TTS since Update

### ISSUE THREAD

**Issue by BeBsCh** [keatontaylor/alexa_media_player#229]
Hello,

since i updated Alexa_media to 0.7.0 i have the error:

Sun Jun 23 2019 13:16:20 GMT+0200 (Mitteleuropäische Sommerzeit)
Error while setting up platform alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/alexa_media/alarm_control_panel.py", line 34, in setup_platform
    hass)  \
  File "/config/custom_components/alexa_media/alarm_control_panel.py", line 73, in __init__
    ['LambdaBridge_AAA/OnGuardSmartHomeBridgeService']
KeyError: 'LambdaBridge_AAA/OnGuardSmartHomeBridgeService'

I copied all files.
Another error is: Unable to find service media_player/alexa_tts

Do you have any Idea? Home Assistant is on version 0.94.4

Thanks !

**Comment by alandtse** [comment]
The error in the log is unrelated to tts and already has an issue. 

We removed the service as it's deprecated. Use [Notify](https://github.com/keatontaylor/alexa_media_player/wiki/Notification-Component) instead.
