### ISSUE TITLE
AttributeError: 'ALEXA API' object has no attribute 'get_guard_details'

### ISSUE THREAD

**Issue by rpitera** [keatontaylor/alexa_media_player#241]
Error while setting up platform alexa_media:

```
2019-07-02 19:04:31 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up platform alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/alexa_media/alarm_control_panel.py", line 35, in setup_platform
    hass)  \
  File "/config/custom_components/alexa_media/alarm_control_panel.py", line 86, in __init__
    data = self.alexa_api.get_guard_details(self._login)
AttributeError: 'AlexaAPI' object has no attribute 'get_guard_details'
```

Error is presented but all other aspects of Alex Media Player appear to work fine.

**System details**
 - Home-assistant 0.95.4 
 - Hassio - Yes
 - alexa_media  1.3.1
 - alexapy (version from `pip show alexapy` or HA startup): 0.5.0

**Comment by alandtse** [comment]
For some reason your hassio isn't updating alexapy. This was introduced in alexapy 0.7.0.  You may have to restart hassio 2-3 times before it truly installs the dependency or try to force an install with `pip install alexapy`.

This shouldn't cause you any issues as long as you don't use Guard. I'll close this for now, but please reopen if updating alexapy doesn't resolve this.

**Comment by rpitera** [comment]
I'll try manually installing and get back to you.

**Comment by rpitera** [comment]
I had 0.5.0 in my deps folder.  I deleted it and restarted HA and it apparently updated the dependency because the error is gone and the alarm control panel entity has been created.  Sorry for the false alarm!  

I'm writing my findings in case anyone else runs into this.
