### ISSUE TITLE
Alexa Guard: TypeError: 'NoneType' object is not subscriptable in init

### ISSUE THREAD

**Issue by alandtse** [keatontaylor/alexa_media_player#243]
Site note (I think not relevant within this issue): The log has an error during setup of component:

```
2019-07-04 10:28:24 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up platform alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/alexa_media/alarm_control_panel.py", line 35, in setup_platform
    hass)  \
  File "/config/custom_components/alexa_media/alarm_control_panel.py", line 88, in __init__
    guard_dict = (data['locationDetails']
TypeError: 'NoneType' object is not subscriptable

```

That is because, alexa guard is not yet available in germany.

_Originally posted by @lweberru in https://github.com/keatontaylor/alexa_media_player/issues/242#issuecomment-508400440_

**Comment by monsieurlatte** [comment]
Just a heads up, I'm not in Germany and I too am seeing this (I am in the U.S.).

**Comment by alandtse** [comment]
@monsieurlatte Just to check, did you set up Alexa Guard? That is also the cause of the error. There is a PR that should resolve this if you want to check it. #245

**Comment by monsieurlatte** [comment]
Yep I did.  Thanks I’ll have a look at the PR. 

On Jul 7, 2019, at 11:07 AM, Alan Tse <notifications@github.com> wrote:

@monsieurlatte Just to check, did you set up Alexa Guard? That is also the cause of the error. There is a PR that should resolve this if you want to check it. #245

**Comment by alandtse** [comment]
@monsieurlatte oh wait, I didn't read your logs fully, that's a different issue. I'm going to move this to a different issue so please respond there.
