### ISSUE TITLE
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity switch

### ISSUE THREAD

**Issue by alandtse** [keatontaylor/alexa_media_player#269]
**Describe the bug**
ha_schedule_update is called before entity_id is assigned on startup

**To Reproduce**
1. Restart HA

**Expected behavior**
Exception should not be thrown

**Screenshots**

**System details**
 - Home-assistant (version): 0.97.0
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 1.4.0
 - alexapy (version from `pip show alexapy` or HA startup): 0.7.1

**Additional context**
Does not seem to degrade functionality

**Comment by KennethLavrsen** [comment]
I am being flooded with errors like this too.

**Comment by alandtse** [comment]
You should only see this on startup and after that you won't see it. Let me know if you see it more than that or if you see functionality problems.

**Comment by snakuzzo** [comment]
same here after upgrade to 1.4.1

**Comment by mauog** [comment]
Same here after moving to HACS and 1.4.1 (previously I had 1.3.1 with custom_updater)
HA is 0.96.5 running in a docker container.

```
2019-08-08 14:16:42 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 216, in async_update_ha_state
    "No entity id specified for entity {}".format(self.name))
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity Ovunque shuffle switch
```
A line for each entities related to Alexa.
It looks that the errors are showed just at the startup

**Comment by anrada73** [comment]
same Problem

**Comment by supersonical** [comment]
I´m having the same problem


homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity This Device repeat switch
2019-08-16 21:00:32 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 243, in async_update_ha_state
    "No entity id specified for entity {}".format(self.name)
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity  Alexa Apps repeat switch
2019-08-16 21:00:32 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 243, in async_update_ha_state
    "No entity id specified for entity {}".format(self.name)
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity  do not disturb switch
2019-08-16 21:00:32 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
