### ISSUE TITLE
KeyError: 'dnd'

### ISSUE THREAD

**Issue by snakuzzo** [keatontaylor/alexa_media_player#270]
**Describe the bug**

**To Reproduce**
1. update alexa_media_player to 1.4.0 version
2. restart homeassistant
3. See error...

```
2019-08-08 09:00:53 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform alexa_media
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 149, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/alexa_media/media_player.py", line 66, in setup_platform
    hass)
  File "/home/homeassistant/.homeassistant/custom_components/alexa_media/media_player.py", line 144, in __init__
    self.refresh(device)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/alexa_media/media_player.py", line 279, in refresh
    self._dnd = device['dnd']
KeyError: 'dnd'
```

**Expected behavior**
No error while starting homeassistant

**System details**
 - Home-assistant (version): 0.97.0
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 1.4.0
 - alexapy (version from `pip show alexapy` or HA startup): 0.7.1

**Comment by alandtse** [comment]
Just to check, what region are you in and do you have a setting to enable [do not disturb](https://www.amazon.com/gp/help/customer/display.html?nodeId=202101990) through the Alexa App?

**Comment by snakuzzo** [comment]
I'm from Europe (Italy) and I have just alexa app (not speakers) and no "do not disturb" enabled

**Comment by snakuzzo** [comment]
but now this issue is solved...I have no KeyError: 'dnd' anymore.
Now I have errors described in issue [268](https://github.com/keatontaylor/alexa_media_player/issues/268) and [269](https://github.com/keatontaylor/alexa_media_player/issues/269)

**Comment by vigonotion** [comment]
Had the same issue, in the German Alexa app. But I do have a toggle switch in the app to turn on/off DND.
It works now.
