### ISSUE TITLE
0.97.0 Could not convert string to float: unknown

### ISSUE THREAD

**Issue by niemyjski** [keatontaylor/alexa_media_player#273]
Using the latest stable versions of everything. I just noticed that I'm getting the following error:

```
2019-08-08 09:04:52 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 45, in async_entity_state_listener
    hass, smart_home_config, alexa_changed_entity
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 68, in async_send_changereport_message
    properties = list(alexa_entity.serialize_properties())
  File "/usr/src/homeassistant/homeassistant/components/alexa/entities.py", line 181, in serialize_properties
    for prop in interface.serialize_properties():
  File "/usr/src/homeassistant/homeassistant/components/alexa/capabilities.py", line 105, in serialize_properties
    prop_value = self.get_property(prop_name)
  File "/usr/src/homeassistant/homeassistant/components/alexa/capabilities.py", line 446, in get_property
    return {"value": float(temp), "scale": API_TEMP_UNITS[unit]}
ValueError: could not convert string to float: 'unknown' 
```

**Comment by alandtse** [comment]
This isn't from the custom component. It's from the built in version. You'll need to open a bug in the main repo.
