### ISSUE TITLE
Error - Unable to serialize to JSON: Object of type coroutine is not JSON serializable

### ISSUE THREAD

**Issue by danielmihalache1983** [keatontaylor/alexa_media_player#302]
Hi, I`m not sure this is alexa_media related but it looks like so.
I get this error:
Version 2.0

`ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1827548752] Unable to serialize to JSON: Object of type coroutine is not JSON serializable
{'id': 2, 'type': 'event', 'event': {'event_type': 'state_changed', 'data': {'entity_id': 'media_player.daniel_s_echo_dot', 'old_state': <state media_player.daniel_s_echo_dot=standby; is_volume_muted=False, media_content_type=standby, media_position_updated_at=2019-08-25T23:11:45.106361+03:00, source=Ugreen-Bluetooth05, source_list=['Local Speaker'], available=True, last_called=True, friendly_name=Daniel's Echo Dot, supported_features=56253 @ 2019-08-26T10:25:47.559961+03:00>, 'new_state': <state media_player.daniel_s_echo_dot=standby; is_volume_muted=False, media_content_type=standby, media_position_updated_at=2019-08-25T23:11:45.106361+03:00, source=<coroutine object AlexaClient._get_source at 0x72b620c0>, source_list=<coroutine object AlexaClient._get_source_list at 0x6f0efd68>, available=True, last_called=True, friendly_name=Daniel's Echo Dot, supported_features=56253 @ 2019-08-26T10:25:47.559961+03:00>}, 'origin': 'LOCAL', 'time_fired': datetime.datetime(2019, 8, 26, 8, 1, 49, 181128, tzinfo=<UTC>), 'context': {'id': '715f4156742e4a23beb612ccf57fdf5e', 'parent_id': None, 'user_id': None}}}`

**Comment by danielmihalache1983** [comment]
Error occurs multiple times through out the day when I actually am not home. So I wasn\`t selecting media source.
Another occurrence is like so:
`
2019-08-26 11:01:51 WARNING (Recorder) [homeassistant.components.recorder] State is not JSON serializable: <state media_player.daniel_s_echo_dot=standby; is_volume_muted=False, media_content_type=standby, media_position_updated_at=2019-08-25T23:11:45.106361+03:00, source=<coroutine object AlexaClient._get_source at 0x72b620c0>, source_list=<coroutine object AlexaClient._get_source_list at 0x6f0efd68>, available=True, last_called=True, friendly_name=Daniel's Echo Dot, supported_features=56253 @ 2019-08-26T10:25:47.559961+03:00>
`

**Comment by danielmihalache1983** [comment]
The worst part is that homeassistant lovelace interface hangs on "loading data" screen.
I had to ssh and manually restart homeassistant.
I disabled alexa_media for now, trying to figure out who triggered the "loading data" screen hang.

**Comment by danielmihalache1983** [comment]
No I don`t have debugging enabled. Could you link to somewhere how can I enable?

Anyway, this bit of info
`source_list=<coroutine object AlexaClient._get_source_list at 0x6f0efd68>`
isn`t generated by alexa_media component?

**Comment by danielmihalache1983** [comment]
Done, will get back with updates.

**Comment by danielmihalache1983** [comment]
I get this 
`
2019-08-27 20:52:04 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/media_player.py", line 199, in _handle_event
    await self.async_schedule_update_ha_state()
TypeError: object NoneType can't be used in 'await' expression
`

**Comment by danielmihalache1983** [comment]
yea. this seems to work now.
while monitoring the logs I also noticed this
`
2019-08-27 21:31:51 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexawebsocket.py", line 135, in process_messages
    await self.on_message(cast(bytes, msg.data))
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexawebsocket.py", line 217, in on_message
    await self.msg_callback(message_obj)
  File "/config/custom_components/alexa_media/__init__.py", line 590, in ws_handler
    serial)
  File "/config/custom_components/alexa_media/__init__.py", line 465, in update_bluetooth_state
    for b_state in bluetooth['bluetoothStates']:
KeyError: 'bluetoothStates'
`

**Comment by danielmihalache1983** [comment]
Sure, will do that once I get back home. Thanks for fixing the issue.

**Comment by skynet01** [comment]
Nice, I finally figured out why my lovelace hangs :) So awesome you were able to fix it so fast, thanks alandtse!
